# Generated by Django 5.2.14 on 2026-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
