# * For pdf and docx or doc extraction
from huggingface_hub import InferenceClient
from groq import Groq
import json
from django.conf import settings
import re
from rapidfuzz import fuzz


def extract_text(file):
    try:
        filename = file.name.lower()

        if filename.endswith(".pdf"):
            import fitz

            doc = fitz.open(stream=file.read(), filetype="pdf")

            text = ""

            for page in doc:
                text += page.get_text()

            return text

        elif filename.endswith(".docx"):
            from docx import Document

            doc = Document(file)

            text = ""

            for para in doc.paragraphs:
                text += para.text + "\n"

            return text

        else:
            return "Unsupported file format"

    except Exception as e:
        return str(e)


def generate_questions(resume, role):
    token = settings.GROQ_API_KEY
    client = Groq(api_key=token)


    prompt = f"""
You are an expert technical interviewer with years of experience conducting interviews at top technology companies.

Your task is to generate interview questions based ONLY on the candidate's resume and the target job role.

Resume:
{resume}

Target Job Role:
{role}

Instructions:

1. Generate EXACTLY 5 interview questions.

2. Difficulty distribution MUST be:

* 2 Easy
* 2 Medium
* 1 Hard

3. Questions should be personalized according to:

* Skills mentioned in the resume
* Projects
* Technologies
* Frameworks
* Experience
* Education (if relevant)

4. Every question should test understanding, practical knowledge, problem-solving ability, or real-world application instead of asking simple definitions.

5. Avoid duplicate or very similar questions.

6. Every question MUST have a list of AT LEAST 8 and AT MOST 15 highly relevant keywords or technical phrases.

7. Keywords MUST be directly related to the expected answer of the question.

8. Keywords should be comprehensive and cover the important concepts that a strong candidate would be expected to mention in their answer. Add MORE relevant keywords whenever necessary to fully represent the expected answer. Do NOT limit the keywords to only the most obvious terms.

9. Keywords should include relevant concepts such as:

* Important technical terms
* Frameworks
* Libraries
* APIs
* Algorithms
* Data structures
* Programming concepts
* Design patterns
* Best practices
* Security concepts
* Database concepts
* Performance optimization
* Error handling
* Testing
* Tools
* Technologies
* Architecture concepts
* Real-world implementation concepts

10. Keywords will later be used for automatic answer scoring. Therefore, keywords MUST represent the important concepts, technologies, approaches, and expected points that a correct and complete answer should contain. Include multiple relevant keywords covering different aspects of the expected answer rather than relying on only a few broad keywords.

11. Keywords MUST NOT be exact sentences or long explanations. Each keyword should be a concise technical term or short technical phrase.

12. STRICT KEYWORD FORMATTING RULE:
    Every keyword MUST contain ONLY:

* English letters A-Z or a-z
* Single spaces between words

13. Keywords MUST NOT contain:

* Hyphens (-)
* Underscores (_)
* Commas (,)
* Periods (.)
* Slashes (/)
* Forward slashes
* Backslashes
* Colons (:)
* Semicolons (;)
* Parentheses ()
* Brackets []
* Curly braces {{}}
* Special characters
* Numbers
* Symbols

14. If a technical term normally contains special characters, REMOVE the special characters and replace them with spaces while preserving the meaning as much as possible.

Examples:

* "Test-driven" → "Test Driven"
* "Test-driven development" → "Test Driven Development"
* "React.js" → "React js"
* "Node.js" → "Node js"
* "Next.js" → "Next js"
* "C++" → "C"
* "C#" → "C"
* "REST API" → "REST API"
* "RESTful API" → "RESTful API"
* "SQLAlchemy" → "SQLAlchemy"
* "scikit-learn" → "scikit learn"
* "machine-learning" → "machine learning"
* "time-complexity" → "time complexity"
* "O(n)" → "time complexity"
* "JWT-based authentication" → "JWT based authentication"

15. IMPORTANT:
    Before returning the JSON, internally verify every keyword and make sure it contains ONLY English letters and spaces. If a keyword contains any hyphen, underscore, punctuation mark, number, symbol, or special character, rewrite it before returning the final JSON.

16. Do NOT include the difficulty level in the output.

17. Return ONLY valid JSON.

18. Do NOT write explanations.

19. Do NOT use markdown.

20. Do NOT use ```json.

21. The JSON object MUST contain exactly 10 keys.

22. Each key MUST be the actual interview question generated by you.
    NEVER use placeholder keys such as:
    - "Question 1?"
    - "Question 2?"
    - "Question 3?"
    - "Question 1"
    - "Question 2"

23. The interview question itself MUST be used as the JSON key, and its value MUST be the list of 8 to 15 relevant keywords for that specific question.

24. Each question MUST have between 8 and 15 keywords.

25. Return the JSON in the following STRUCTURE. The questions shown below are ONLY examples to demonstrate the structure. DO NOT copy these questions. Generate completely new questions based on the resume and target job role.

{{
  "How did you implement authentication in your Django project and how did you handle token security?": [
    "Django",
    "authentication",
    "JWT",
    "access token",
    "refresh token",
    "token security",
    "user authentication",
    "API security"
  ],
  "How did you optimize database queries in your project when working with Django?": [
    "Django",
    "database queries",
    "query optimization",
    "Django ORM",
    "database indexing",
    "select related",
    "prefetch related",
    "performance optimization"
  ]
}}

26. IMPORTANT:
    The questions in the example above are ONLY for demonstrating the JSON format.
    Do NOT return these exact questions unless they are genuinely relevant to the candidate's resume and target job role.

27. The final JSON MUST contain exactly 10 unique, personalized interview questions as keys.

28. NEVER output placeholder keys such as "Question 1?", "Question 2?", or "Question 1".

29. Every JSON key must be a complete and meaningful interview question based on the candidate's resume and target job role.
"""


    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.3
    )

    response_text = response.choices[0].message.content

    print("RAW RESPONSE:")
    print(response_text)
    
    clean_response = response_text.strip()

    if clean_response.startswith("```json"):
        clean_response = clean_response.replace("```json", "", 1)

    if clean_response.startswith("```"):
        clean_response = clean_response.replace("```", "", 1)

    if clean_response.endswith("```"):
        clean_response = clean_response[:-3]

    try:
        return json.loads(clean_response.strip())
    except json.JSONDecodeError:
        print("Failed to decode JSON")
        print(clean_response)
        return {}


# SPEECH_TO_TEXT_MAP = {
#     # Frameworks & Libraries
#     "jango": "django",
#     "d jango": "django",
#     "giango": "django",
#     "react js": "react",
#     "reactjs": "react",
#     "node js": "node",
#     "nodejs": "node",
#     "next js": "next",
#     "vue js": "vue",

#     # Languages
#     "c sharp": "c#",
#     "see sharp": "c#",
#     "sea sharp": "c#",
#     "c plus plus": "c++",
#     "type script": "typescript",
#     "java script": "javascript",
#     "pie thon": "python",

#     # Databases & Tools
#     "sequel": "sql",
#     "postgress": "postgresql",
#     "postgres": "postgresql",
#     "postgre sql": "postgresql",
#     "mongo db": "mongodb",
#     "my sequel": "mysql",
#     "my sql": "mysql",
#     "graph ql": "graphql",
#     "dock er": "docker",
#     "coobernetes": "kubernetes"
# }


# def clean_text(text):
#     """Converts text to lowercase and replaces known speech-to-text errors."""
#     text = text.lower()

#     # Replace misspoken terms with correct keywords
#     for wrong_word, correct_word in SPEECH_TO_TEXT_MAP.items():
#         text = text.replace(wrong_word, correct_word)

#     return text


def get_score(answer, keywords, question_text):
    """Calculates score out of 10 using an LLM to evaluate the answer, handling STT transcription errors."""
    if not answer or not str(answer).strip():
        return 0.0

    token = settings.GROQ_API_KEY
    client = Groq(api_key=token)

    # Convert keywords list to a comma-separated string for the prompt
    expected_concepts = ", ".join(keywords) if keywords else "None specified"

    prompt = f"""
You are an expert technical interviewer and senior software engineer evaluating a candidate's spoken answer during a technical interview.

Your task is to evaluate the candidate's answer ONLY in relation to the given interview question and expected technical concepts.

INTERVIEW QUESTION:
{question_text}

EXPECTED TECHNICAL CONCEPTS:
{expected_concepts}

CANDIDATE ANSWER:
{answer}

SCORING OBJECTIVE:

Give the candidate a score from 1 to 10 based on the overall quality of their answer.

The score MUST reflect:

* Technical correctness
* Relevance to the question
* Understanding of the topic
* Coverage of important expected concepts
* Depth of explanation
* Practical understanding
* Accuracy of technical terminology
* Ability to explain concepts correctly
* Completeness of the answer

CRITICAL SPEECH TO TEXT INSTRUCTION:

The candidate's answer was generated using Speech to Text technology, such as the Web Speech API.

Speech to Text transcription may contain:

* Phonetic misspellings
* Homophones
* Incorrect spacing
* Missing punctuation
* Incorrect capitalization
* Partial words
* Misheard technical terms
* Words that sound similar to technical terms
* Unnatural sentence structure
* Repeated words
* Minor grammar mistakes

Examples of possible transcription errors:

* "django" → "jango"
* "django" → "d jango"
* "Django REST Framework" → "jango rest framework"
* "C sharp" → "sea sharp"
* "C#" → "C sharp"
* "SQL" → "sequel"
* "React.js" → "react js"
* "Node.js" → "node js"
* "JavaScript" → "java script"
* "PostgreSQL" → "post gres"
* "MongoDB" → "mongo db"
* "API" → "A P I"
* "JWT" → "J W T"
* "Redis" → "red is"

You MUST interpret the candidate's intended meaning using semantic understanding and contextual reasoning.

DO NOT penalize the candidate for:

* Speech to Text transcription mistakes
* Phonetic spelling errors
* Homophones
* Missing punctuation
* Capitalization differences
* Minor grammatical mistakes
* Minor sentence structure problems
* Spoken-language filler words such as "um", "uh", "like", or "you know"
* Slightly incorrect wording when the intended technical concept is clearly correct

TECHNICAL EVALUATION RULES:

1. Evaluate the candidate's actual technical understanding, NOT exact keyword matching.

2. The expected technical concepts are GUIDELINES for evaluating the answer. The candidate does NOT need to use the exact words from the expected concepts.

3. Give credit when the candidate explains the same concept using different words, synonyms, examples, or descriptions.

4. Do NOT require the candidate to mention every expected concept if the answer demonstrates strong overall understanding.

5. However, if the candidate completely misses important core concepts that are essential to answering the question, reduce the score appropriately.

6. A keyword mentioned without correct understanding should NOT receive full credit.

7. If the candidate mentions a technically incorrect concept, misleading information, or an incorrect explanation, reduce the score based on the severity of the mistake.

8. Minor technical imprecision should result in a smaller deduction than a fundamentally incorrect explanation.

9. If the candidate gives a correct practical example that demonstrates understanding of an expected concept, give credit even if the candidate does not explicitly mention the expected keyword.

10. If the candidate provides additional technically correct and relevant information that is not included in the expected concepts, consider it positively.

11. Do NOT reward irrelevant technical buzzwords that are unrelated to the question.

12. Do NOT assume that a keyword is correctly understood merely because it appears in the answer. Evaluate the context in which the candidate uses it.

13. If the answer is short but technically correct and directly answers the question, give appropriate credit. Do not automatically give a low score only because the answer is brief.

14. If the question requires explanation of multiple concepts and the candidate explains only one small part correctly, give partial credit.

15. If the candidate's answer contains technically correct concepts but is poorly structured, prioritize technical correctness over grammar and speaking style.

16. If the candidate gives a correct answer using an alternative technology, approach, or implementation that is valid for the question, give credit when appropriate.

17. Do not penalize the candidate simply because they use a different valid implementation approach from the expected concepts.

ANSWER RELEVANCE:

* If the answer directly addresses the question and demonstrates technical understanding, score normally.
* If the answer is partially relevant but misses important parts of the question, give a partial score.
* If the answer is mostly unrelated to the question, give a low score.
* If the answer is completely unrelated, meaningless, or contains no meaningful technical content, give a score between 1 and 2.
* If the answer is technically incorrect and demonstrates a fundamental misunderstanding, give a score between 1 and 3.

SCORING GUIDELINE:

1 to 2:

* Completely unrelated, meaningless, or no meaningful technical understanding.
* Fundamental misunderstanding of the question.

3 to 4:

* Very limited understanding.
* Some relevant information but mostly incorrect, incomplete, or superficial.
* Major technical misunderstandings.

5 to 6:

* Basic to moderate understanding.
* Some important concepts are correct.
* Answer is relevant but incomplete or lacks depth.
* May contain some technical inaccuracies.

7 to 8:

* Good technical understanding.
* Mostly correct and relevant.
* Covers most important concepts.
* Demonstrates practical understanding.
* Minor omissions or inaccuracies may exist.

9:

* Excellent answer.
* Technically accurate and highly relevant.
* Covers nearly all important concepts.
* Demonstrates strong understanding and practical knowledge.
* Very minor omissions, if any.

10:

* Exceptional answer.
* Fully correct, comprehensive, relevant, and technically accurate.
* Demonstrates deep understanding rather than simple keyword repetition.
* Covers the essential expected concepts.
* Provides strong reasoning, practical examples, tradeoffs, or real-world understanding when relevant to the question.

IMPORTANT FINAL RULES:

* Score ONLY the candidate's answer to the provided question.
* Do NOT evaluate the candidate's overall resume or overall interview performance.
* Do NOT assume knowledge that the candidate did not demonstrate.
* Do NOT penalize Speech to Text errors.
* Do NOT require exact keyword matches.
* Do NOT give a high score merely because many keywords appear.
* Do NOT give a low score merely because the answer is short if it is technically correct.
* Consider semantic meaning and technical intent.
* Use your best judgment as an experienced technical interviewer.

OUTPUT FORMAT:

Return ONLY ONE numerical score between 1 and 10.

Floating point scores are allowed, such as:
7.5
8.2
9.0

DO NOT return:

* Explanations
* Feedback
* Comments
* Labels
* Words
* Markdown
* JSON
* Quotes
* Score prefixes such as "Score:"

Your entire response MUST contain ONLY the numerical score.

FINAL OUTPUT:
"""


    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.1  # Keep temperature low for consistent, strict numerical outputs
        )

        score_text = response.choices[0].message.content.strip()

        # Safety net: Extract only the float/int from the response in case the LLM hallucinates text
        match = re.search(r"([0-9]*\.?[0-9]+)", score_text)
        if match:
            score = float(match.group(1))
            # Ensure the score stays within the 0 to 10 boundary
            return max(0.0, min(10.0, round(score, 2)))
        else:
            print(f"Failed to parse score from LLM response: {score_text}")
            return 0.0

    except Exception as e:
        print(f"Error calculating LLM score: {e}")
        return 0.0


def analyze_resume(resume_text, role):
    token = settings.GROQ_API_KEY
    client = Groq(
        api_key=token
    )

    prompt = f"""
You are an expert ATS Resume Analyzer.

Analyze the resume for the given job role.

IMPORTANT:
- Return ONLY a valid JSON object.
- Do NOT include explanations.
- Do NOT include markdown.
- Do NOT use ```json.
- Do NOT write any text before or after the JSON.

Return exactly this format:

{{
  "ats_score": 0,
  "resume_score": 0,
  "skills_found": [],
  "missing_skills": [],
  "strengths": [],
  "weaknesses": []
}}

Resume:
{resume_text}

Job Role:
{role}
"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.7
    )

    response_text = response.choices[0].message.content

    print("RAW RESPONSE:")
    print(response_text)

    clean_response = response_text.strip()
    if clean_response.startswith("```json"):
        clean_response = clean_response.replace("```json", "", 1)
    if clean_response.startswith("```"):
        clean_response = clean_response.replace("```", "", 1)
    if clean_response.endswith("```"):
        clean_response = clean_response[:-3]

    try:
        # Convert the raw string JSON response into a Python dictionary
        resume_dict = json.loads(clean_response.strip())
        return resume_dict
    except json.JSONDecodeError:
        # Fallback mechanism if the model outputs malformed JSON
        print("Failed to decode model output into JSON.")
        return {}
    

